# Exercise 1: Introduction to Python and Jupyter Lab

## Basic Python

Check the tutorial `exercise_01_intro-python_tutorial.ipynb` before you start working on these exercises.

### Use Python as a calculator to compute 256²

In [1]:
256 * 256

65536

In [2]:
hello = "Hello"
world = "World!"
print(hello + world)
print(hello + " " + world)

HelloWorld!
Hello World!


### Create a list that contains the 4 strings "alpha", "beta", "gamma", and "delta". Add "epsilon" to the end of this list

In [2]:
l = ["alpha", "beta", "gamma", "delta"]
l.append("epsilon")
l

['alpha', 'beta', 'gamma', 'delta', 'epsilon']

In [3]:
# appending via overloaded '+' operator
l = l + ["omega"]
l

['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'omega']

### Create a sublist with the first three elements of this list


In [ ]:
# note: index on the left side of column is index After the final element we want to include
l2 = l[:3] # -> this returns elements at indices 0,1,2
l2

### Write a Python program to construct the following pattern using for loops

In [ ]:
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
*

In [5]:
"*" * 5

'*****'

In [5]:
ll = list(range(1,5)) + list (range (5,0,-1))
print(ll)

# for loop syntax, indentation indicates what is inside of the loop
for i in ll:
    print("* " * i)

[1, 2, 3, 4, 5, 4, 3, 2, 1]
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


### Write a function that takes 3 input parameters and returns the product of these values

In [7]:
def my_product(x,y,z):
    return x*y*z

my_product(2,3,4)

24

In [8]:
# * operator actually allows arbitrary number of arguments
# function definition, again, structure determined via indentation
def my_product (*x):
    result = 1
    for elem in x:
        result = result * elem
    return result

In [10]:
my_product(2,3,4,5,6,10)

7200

### Write a Python function that takes an int as a parameter and checks if the number is prime or not.

In [12]:
x = 20
y = 6
x % y == 0

False

In [13]:
from math import sqrt

In [33]:
def is_prime(x):
    for y in range(2,int(x**0.5) + 1):
        if x % y == 0:
            return False
    return True

In [34]:
x= 2
int(x**0.5) + 1

2

In [35]:
is_prime(2)

True

In [36]:
def is_prime (x):
    for n in range (2, x // 2 + 1):
        if x % n == 0: # if-clause, uses modulo operator
            return False
    return True

print (is_prime (12))
print (is_prime (13))
print (is_prime (23))
print (is_prime (21))

False
True
True
False


### Use your function to create a list that contains all primes from 2 to 100

In [39]:
def primes_up_to (n):
    return [x for x in range(2, n+1) if is_prime(x)]

primes_up_to(100)

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

In [37]:
# solve via another helper function
def primes_up_to (n):
    result = []
    for x in range (2, n+1):
        if is_prime(x):
            result.append(x)
    return result

primes_up_to(100)

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

### Write a function that simulates dice rolls (6-sided dices)
- Write a function that has the number of dice rolls as the input parameter
- The output is a map with the counts how often each result of a roll (1-6) occurred
- You can use the randomint() function from the random package

In [ ]:
# load the random package
import random

In [40]:
import random # how to import installed libraries

def roll (n):
    result = {1:0, 2:0, 3:0, 4:0, 5:0, 6:0} # manual definition of a dictionary -> listing of key:value pairs
    for i in range (n):
        r = random.randint(1,6)
        result [r] = result[r] + 1 #access to value via key -> hashmap principle
    return result

roll (60000)

{1: 10125, 2: 9943, 3: 10136, 4: 9860, 5: 10099, 6: 9837}

### Combine two dictionaries by adding values for common keys.
d1 = {'a': 100, 'b': 200, 'c':300}

d2 = {'a': 300, 'b': 200, 'd':400}

Sample output: {'a': 400, 'b': 400, 'd': 400, 'c': 300}

In [9]:
d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}

d = {}

# iteration over key-value pairs via items()
for k,v in d1.items():
    d[k] = v
for k,v in d2.items():
    if k in d:
        d [k] = d[k] + v
    else:
        d[k] = v
d

{'a': 400, 'b': 400, 'c': 300, 'd': 400}

### Create a list of lists. Then, write a list comprehension that creates a list with the lengths of each (sub)list in the primary list

In [10]:
test_l = [[1,2,3],["a", "b"], [123.5, "a", 44]]
[len(t) for t in test_l] # loop in list comprehension

[3, 2, 3]

### Exceptions

Write your own function *my_division* that gets two variables a and b and returns a divided by b. Catch the ZeroDivisionError that occurs if b equals 0 and return 1 in this case.

How could the same behavior be achieved without catching an exception?

In [11]:
def my_division (a, b):
    try: 
        return a / b
    except ZeroDivisionError: # call specific error, try-except also works without specifying error
        return 1

print (my_division (20,5))
print (my_division (20,0))

4.0
1


In [12]:
# same function without catching exception
def my_division2 (a, b):
    if b==0: 
        return 1
    else:
        return a/b

print (my_division2 (20,5))
print (my_division2 (20,0))

4.0
1


### File handling

Write a function that gets a letter and the path to a (text-)file on your harddrive as input parameters and computes a list as its output. The list should contain one number for each line. The i-th line shows, how often the given letter occurs in line number i in the text file. Test your function on "ftest.txt", which was provided in this exercise!

In [20]:
def count_letter (letter, filename):
    result = []
    # with -- as to create alias
    with open(filename, "r") as f: #r ==> open for reading
        for line in f: # overloaded 'in' iterates over rows in file
            result.append(line.count(letter)) #built-in count() function for strings
    return result

In [22]:
count_letter('a',"test.txt")

[11, 22, 9]

## Numpy

In this last set of tasks, you will have to work with [numpy](https://numpy.org/), the the fundamental package for scientific computing with Python.
Make sure to execute the cell below to import the package, we will usually use the abbreviation np for numpy to obtain shorter code.

In [23]:
import numpy as np

### Create a numpy array with 20 rows and 10 columns, where all values are set to zero

In [27]:
x = np.zeros ((20,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
# Tedious: direct specification of a array/matrix (here only 2x2)
x =np.array([[0,0],
          [0,0]])

### Create an array with the same shape containing all natural numbers 0-199

In [29]:
# np.arange similar to range
np.arange(200).reshape((20,10))

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

### Create a 4-dimensional array with exactly 16 elements and set all values to a random integer smaller than 5

In [30]:
x = np.random.randint(5, size=(2,2,2,2))
x

array([[[[0, 1],
         [0, 2]],

        [[3, 1],
         [3, 2]]],


       [[[4, 3],
         [4, 3]],

        [[4, 0],
         [3, 0]]]])

### What is the mean of all values contained in this array?

In [31]:
x.mean()

2.0625

### Select a sub-array containing exactly two elements of that array!

In [32]:
x[1,1,1,:]

array([3, 0])

### Given a numpy array, return a new numpy array that contains only the elements that are greater than 100

In [54]:
x = np.array([120,-5,150,250,300,50,112])
x[x > 100]

array([120, 150, 250, 300, 112])

In [55]:
# works via indexing with array of boolean values
x > 100

array([ True, False,  True,  True,  True, False,  True])

## Pandas

> **pandas** is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.<br/>[(source)](https://pandas.pydata.org/)

We will do a couple of simple things here. For more material see:
* [10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html) (this is probably more than ten minutes ;))
* [Pandas tutorial by Kaggle](https://www.kaggle.com/learn/pandas)

In [8]:
import pandas as pd

### Read the CSV file `exercise_01_titanic.csv` using pandas.

* see [`read_csv` documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) for an example
* make sure the `index` is set to the `PassengerId`

In [9]:
data_titanic = pd.read_csv("exercise_01_titanic.csv", index_col="PassengerId")

### Display the first/last five rows the dataset you loaded

In [10]:
data_titanic.head(5)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [11]:
data_titanic.tail(5)

Survived  Pclass                                      Name  \
PassengerId                                                               
887                 0       2                     Montvila, Rev. Juozas   
888                 1       1              Graham, Miss. Margaret Edith   
889                 0       3  Johnston, Miss. Catherine Helen "Carrie"   
890                 1       1                     Behr, Mr. Karl Howell   
891                 0       3                       Dooley, Mr. Patrick   

                Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
PassengerId                                                                
887            male  27.0      0      0      211536  13.00   NaN        S  
888          female  19.0      0      0      112053  30.00   B42        S  
889          female   NaN      1      2  W./C. 6607  23.45   NaN        S  
890            male  26.0      0      0      111369  30.00  C148        C  
891            male  32.0      0      0      370376   7.75   NaN        Q

### Use the `describe` method to look at the features in the dataset.

In [13]:
data_titanic.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

### Select the `Survived` variable and store it in `y`

In [16]:
y = data_titanic["Survived"]
y

PassengerId
1      0
2      1
3      1
4      1
5      0
      ..
887    0
888    1
889    0
890    1
891    0
Name: Survived, Length: 891, dtype: int64

### Select all variables of type `numeric` except `Survived` and store it in `X`

*Hint*: Use panda's `select_dtypes`.

In [24]:
X = data_titanic.iloc[:, 1:].select_dtypes(np.number)
X

Pclass   Age  SibSp  Parch     Fare
PassengerId                                     
1                 3  22.0      1      0   7.2500
2                 1  38.0      1      0  71.2833
3                 3  26.0      0      0   7.9250
4                 1  35.0      1      0  53.1000
5                 3  35.0      0      0   8.0500
...             ...   ...    ...    ...      ...
887               2  27.0      0      0  13.0000
888               1  19.0      0      0  30.0000
889               3   NaN      1      2  23.4500
890               1  26.0      0      0  30.0000
891               3  32.0      0      0   7.7500

[891 rows x 5 columns]

### Calculate the number of NAs (not defined values) for each variables in `X`

In [26]:
X.isna().sum()

Pclass      0
Age       177
SibSp       0
Parch       0
Fare        0
dtype: int64

Also, which variable has the most NAs?

In [28]:
X.columns[np.argmax(X.isna().sum())]

'Age'

### Calculate the mean, standard deviation, size and the number of defined values for the `Age` for each `Pclass`

*Hint*: Use `groupby`

In [42]:
data_titanic[["Pclass", "Age"]].groupby("Pclass").agg(["mean", "std", "size", "count"])

Age                      
             mean        std size count
Pclass                                 
1       38.233441  14.802856  216   186
2       29.877630  14.001077  184   173
3       25.140620  12.495398  491   355

## Plotting

The `matplotlib` library is one of the main libraries for visualziations in Python. `seaborn` builds on `matplotlib` and provides easier access to common plotting scenarios.

### Matplotlib

1) Follow the [pyplot tutorial](https://matplotlib.org/stable/tutorials/introductory/pyplot.html) including *"Plotting with categorical variables"*.
2) Apply at least one of the plots to the titanic dataset from above.

*Note*: It makes sense to eventually learn the "object oriented" `matplotlib` API (also see [here](https://matplotlib.org/stable/tutorials/introductory/pyplot.html)).

### Seaborn

1) Follow the [`seaborn` introduction](https://seaborn.pydata.org/tutorial/introduction.html) until *"Plots for categorical data"*.
2) Apply at least one of the plots to the titanic dataset from above.

## Bonus

* Fit a model that predicts whether a passenger `Survived` using [Scikit-Learn](https://scikit-learn.org/stable/). See the [supervised machine learning tutorial](https://scikit-learn.org/stable/tutorial/statistical_inference/supervised_learning.html) for reference.
* Evaluate the performance of your model.
* Try to optimize your model.