# Tutorial 1: Introduction to Python and Jupyter Lab

## Install Jupyter Lab using Anaconda

1) Install [Anaconda](https://www.anaconda.com/products/distribution) (or [miniconda](https://docs.conda.io/en/latest/miniconda.html) or [mamba](https://mamba.readthedocs.io/en/latest/installation.html) if you know what you are doing)
2) [Install](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html) and [run](https://jupyterlab.readthedocs.io/en/stable/getting_started/starting.html) JupyterLab

**Alternatively** you can upload these tutorials to [Google Colab](https://colab.research.google.com/) (no installation required).

## Variables and data types

Execute the cell with `Shift+Enter` or `Ctrl+Enter`:

Click on the left of a cell to get into the "blue" mode then you can press:
* a -> new cell above the current cell
* b -> new cell below the current cell
* x -> delete the current cell

Click within a cell to get into the "green" mode (edit mode). Now you can write code here.


In [1]:
# print statements give out information
print ("Hello")
print ("World")


Hello
World


In [2]:
x = "Hello!"
print(x)

y = "Hello"
x = " World"
print (y + x)

x = 5
y = 2
print (x + y)

Hello!
Hello World
7


In [3]:
x

5

In [4]:
print (4+5)
print (x == 10)

9
False


In [6]:
x = "Hello"
y = "World"
print (x + y)

HelloWorld


In [14]:
#Python is dynamically typed, types can change:
x = "hello"
print (x)
x = 5
print (x)

hello
5


In [15]:
#main data types:
x = 5
print(type(x))

x = 5.0
print(type(x))

x = "5"
print(type(x))

x = True
print(type(x))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [7]:
# Python is strongly typed
x = "5"
y = 2
x+y

TypeError: can only concatenate str (not "int") to str

In [ ]:
type(x)

In [ ]:
x = "5"
y = "4"
int(x)+int(y)

## Data structures

### Lists

In [ ]:
#creating an empty list
l = []

In [ ]:
# adding elements to the list
l.append (2)
l.append (5)
l.append (10)
l

In [ ]:
l[1]

In [ ]:
# accessing an element
l[-1]


In [ ]:
l [:-1]

In [ ]:
#setting an element 
l[2] = 7.3
l

In [ ]:
#the length of a list:
len (l)

In [ ]:
# We can also directly specify lists:
# a list with integer objects
list_2 = [3,5,7,9]

# a list of strings
list_3 = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

# a list of mixed types
list_4 = [2, 5, "Elephant", 6, 8.2, True]

In [ ]:
# we can also do lists of lists!
lol = [[1,2,3], ["a","b","c"], [1.2,2.3,4.5,6.7,8.9]]

In [ ]:
#the length of a list:
len (lol)

### Tuples

Tuples are just the same as lists, but are *immutable*.

In [ ]:
t = (1,2,3)

In [ ]:
t[1]

In [ ]:
t[1] = 5

### Sets

Sets are similar collections, but have no order and can contain each element only once

In [ ]:
s = set()
s.add(50)
s.add(20)
s.add(10)
s.add(20)
s

In [ ]:
l = [2,3,4,5,6,2,3,4,5,2]

In [ ]:
s = set()
for x in l:
    s.add(x)
s

In [ ]:
list (set(l))

### Dictionaries

 Python’s built-in mapping type. They map keys, which can be any immutable(unchanchable) type, to values, which can be any type

In [ ]:
d = dict()
d = {}

In [ ]:
presidents_inauguration = {}
presidents_inauguration ['Trump'] = 2017 
presidents_inauguration['Obama'] = 2009
presidents_inauguration['Bush'] = 2001
print(presidents_inauguration)

In [ ]:
# or, shorter:
presidents_inauguration = {'Trump': 2017, 
                           'Obama': 2009, 
                           'Bush': 2001}

In [ ]:
presidents_inauguration ["Trump"]

In [ ]:
print (presidents_inauguration.keys())
print (presidents_inauguration.values())

In [ ]:
len (presidents_inauguration)

## Control statements

control flow in Python noticeable does not use ANY (,),[,],{,},...
Instead *indendation* determines what belongs to block of commands

### If-elif-else

In [ ]:
x = 10
if x > 5:
    print ('This is a big number!')


In [ ]:
#Note the difference
x = 0
y = 0
if x > 5:
    x = x + 1
    y = y + 1
print (y)

x = 0
y = 0
if x > 5:
    x = x + 1
y = y + 1
print (y)

In [ ]:
x = 15
if x > 20:
    print ('This is a very big number!')
elif x > 10:
    print ('This is a big number!')
else:
    print ('this is a small number!')

In [ ]:
x = 10
command = 'increment'
if command =='increment':
    x = x + 1
print (x)

### Loops

In [ ]:
first_names = ['John', 'Paul', 'George', 'Ringo']
for name in first_names:
    print("Hello " + name + "!")

Contrary to many other programming languages there is no built-in for... counting loop.
However, you can use the range function:


In [ ]:
list (range(10,20,3))

In [ ]:
for i in range (10):
    print (i)

In [ ]:
# enumerate is a useful convenience functions:
for index, name in enumerate (first_names):
    print("Name "+ str(index) + ": " + name)

In [ ]:
# We can loop over any iterable, e.g., also on strings
x = "example"
for letter in x:
    print (letter)

In [ ]:
# As a simple example, lets create a dictionary, which maps each string in a list to its name:
name_lengths = {}
for name in first_names:
    name_lengths [name] = len (name)
name_lengths

In [ ]:
# while loops functions very similar to many popular languages:
x = 1
while True:
    x = x * 2
    if x >= 100:
        break
    print(x)
    

## Functions

Defining your own functions is easy:

In [ ]:
l = [1,2,3,4,5324,2,5,2,3,65,2]
len(l)

In [ ]:
def print_all_names(names):
    for x in names:
        print (x)

In [ ]:
print_all_names(l)

In [ ]:
def increment_function(x):
    x = x + 1
    return x

In [ ]:
increment_function(5)

In [8]:
# You can call a function using its parameters names
def my_division (nominator,denominator):
    return nominator / denominator

print (my_division(12,4))
# you can call function parameters by name!
print (my_division(denominator=4, nominator=16))

3.0
4.0


In [9]:
# You can also specify default parameters for a function
def my_division (nominator,denominator = 2):
    return nominator / denominator

print (my_division(12,3))

4.0


In [10]:
# n
y = 5
x = 2
def increment_value (x):
    y = x + 1
    return y
increment_value(3)
y

5

## Imports

Python has a lot of built-in packages you can use, or you can download and install more packages from the internet.
Using such packages is easy:

In [ ]:
import statistics

statistics.mean([3,5,7,9])

In [ ]:
# you can also import just single functions from a package
from math import log
log (2.71 * 2.72)

## List Comprehension

In [ ]:
my_list = [2,6,5,4,66,9,100,55,4,6,4,2]

l2 = [2*x for x in my_list]
l2

In [ ]:
l3 = []
for x in my_list:
    l3.append(2*x)
l3

In [ ]:
my_list = [2,6,5,4,66,9,100,55,4,6,4,2]

new_list = [len(str(x)) for x in my_list if x > 20]
new_list

In [ ]:
nl = []
for x in my_list:
    if x > 20:
        nl.append(x*2)
nl

## numpy


In [10]:
import numpy as np

x = np.array([1,2,3])
x * 4

array([ 4,  8, 12])

In [11]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
m * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [13]:
m.dot(x)

array([14, 32, 50])

In [14]:
m[1,2]

6